2024-08-28 19:08:21,482 - app - INFO - PoetryBackend startup
2024-08-28 19:08:43,916 - app - INFO - PoetryBackend startup
2024-08-28 19:08:47,783 - app - ERROR - Exception on /user/poems [GET]
Traceback (most recent call last):
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: get_user_poems() missing 1 required positional argument: 'user_id'
2024-08-28 19:08:47,785 - app - ERROR - Exception on /user/poems [GET]
Traceback (most recent call last):
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/malladipradyumna/Desktop/Vurbalize/PoetryBackend/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
TypeError: get_user_poems() missing 1 required positional argument: 'user_id'
2024-08-28 19:09:14,450 - app - INFO - PoetryBackend startup
2024-08-28 19:09:30,621 - app - INFO - PoetryBackend startup
2024-08-28 19:11:00,351 - app - INFO - PoetryBackend startup
2024-08-28 19:11:18,332 - app - INFO - PoetryBackend startup
2024-08-28 19:27:27,836 - app - INFO - PoetryBackend startup
2024-08-28 19:45:13,009 - app - INFO - PoetryBackend startup
2024-08-28 20:37:53,694 - app - INFO - PoetryBackend startup
2024-08-28 20:44:29,892 - app - INFO - PoetryBackend startup
2024-08-28 20:49:28,954 - app - INFO - PoetryBackend startup
2024-08-28 22:28:29,534 - app - INFO - PoetryBackend startup
2024-08-28 22:29:08,416 - app - INFO - PoetryBackend startup
2024-08-28 22:29:17,645 - app - INFO - PoetryBackend startup
2024-08-28 22:31:36,221 - app - INFO - PoetryBackend startup
2024-08-29 00:01:02,445 - app - INFO - PoetryBackend startup
2024-08-29 00:01:06,481 - app - INFO - PoetryBackend startup
2024-08-29 00:11:41,769 - app - INFO - PoetryBackend startup
2024-08-29 00:11:47,149 - app - INFO - PoetryBackend startup
